// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar_Menu from "@/components/Navbar_Menu";
// import MobileNavbar from "@/components/MobileNavbar";
// import Footer from "@/components/Footer";
// import "bootstrap/dist/css/bootstrap.min.css";
// import "slick-carousel/slick/slick.css";
// import "slick-carousel/slick/slick-theme.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <head>
//         <link rel="icon" type="image/jpeg" href="/media/nnclogo.png" />
//         <title>
//           Nakshatra Namaha Creations | Website Developers in Bangalore
//         </title>
//         <meta
//           name="description"
//           content="Nakshatra Namaha Creationsis is best website developers in Bangalore, specializes in creating custom, user-friendly and responsive websites for your online presence."
//         />
//         <link
//           href="https://fonts.googleapis.com/css2?family=Poppins:wght@600;700;800;900&display=swap"
//           rel="stylesheet"
//         />
//         <link
//           href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;700&display=swap"
//           rel="stylesheet"
//         />

//         <link
//           href="https://fonts.googleapis.com/css2?family=Anton&display=swap"
//           rel="stylesheet"
//         />
//       </head>
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         <Navbar_Menu />
//         <MobileNavbar />
//         {children}
//         <div style={{ backgroundColor: "#002A3A" }}>
//           <Footer />
//         </div>
//       </body>
//     </html>
//   );
// }

// "use client";

// import { useEffect, useState } from "react";
// import Preloader from "@/components/Preloader";
// import Navbar_Menu from "@/components/Navbar_Menu";
// import MobileNavbar from "@/components/MobileNavbar";
// import Footer from "@/components/Footer";
// import { Geist, Geist_Mono } from "next/font/google";
// import "bootstrap/dist/css/bootstrap.min.css";
// import "slick-carousel/slick/slick.css";
// import "slick-carousel/slick/slick-theme.css";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export default function RootLayout({ children }) {
//   const [progress, setProgress] = useState(0);
//   const [isLoading, setIsLoading] = useState(true);

//   useEffect(() => {
//     // Simulate progress increase
//     const interval = setInterval(() => {
//       setProgress((prev) => {
//         if (prev >= 100) {
//           clearInterval(interval);
//           return 100;
//         }
//         return prev + Math.floor(Math.random() * 10) + 5;
//       });
//     }, 100);

//     // Mark loading complete
//     const timeout = setTimeout(() => {
//       setIsLoading(false);
//     }, 2200); // Time to show preloader (simulate)

//     return () => {
//       clearInterval(interval);
//       clearTimeout(timeout);
//     };
//   }, []);

//   return (
//     <html lang="en">
//       <head>
//         <link rel="icon" href="/media/nnclogo.png" type="image/png" />
//         <title>
//           Nakshatra Namaha Creations | Website Developers in Bangalore
//         </title>
//         <meta
//           name="description"
//           content="Nakshatra Namaha Creations is the best website developer in Bangalore."
//         />
//       </head>
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         {isLoading ? (
//           <Preloader progress={progress} onComplete={() => setIsLoading(false)} />
//         ) : (
//           <>
//             <Navbar_Menu />
//             <MobileNavbar />
//             {children}
//             <div style={{ backgroundColor: "#002A3A" }}>
//               <Footer />
//             </div>
//           </>
//         )}
//       </body>
//     </html>
//   );
// }

"use client";

import { useEffect, useState } from "react";
import Preloader from "@/components/Preloader";
import Navbar_Menu from "@/components/Navbar_Menu";
import MobileNavbar from "@/components/MobileNavbar";
import Footer from "@/components/Footer";
import "bootstrap/dist/css/bootstrap.min.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./globals.css"; // You can define your custom font here via @font-face or CSS import
import BottomNav from "@/components/BottomNav";
import WhatsAppButtons from "@/components/WhatsApp";

export default function RootLayout({ children }) {
  const [progress, setProgress] = useState(0);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const interval = setInterval(() => {
      setProgress((prev) => {
        if (prev >= 100) {
          clearInterval(interval);
          return 100;
        }
        return prev + Math.floor(Math.random() * 10) + 5;
      });
    }, 100);

    const timeout = setTimeout(() => {
      setIsLoading(false);
    }, 2200);

    return () => {
      clearInterval(interval);
      clearTimeout(timeout);
    };
  }, []);

  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/media/nnclogo.png" type="image/png" />
        <title>
          Nakshatra Namaha Creations | Website Developers in Bangalore
        </title>
        <meta
          name="description"
          content="Nakshatra Namaha Creations is the best website developer in Bangalore."
        />
      </head>
      <body>
        {isLoading ? (
          <Preloader
            progress={progress}
            onComplete={() => setIsLoading(false)}
          />
        ) : (
          <>
            <Navbar_Menu />
            <MobileNavbar />
            {children}
            <div style={{ backgroundColor: "#002A3A" }}>
              <Footer />
              <BottomNav />
              <WhatsAppButtons />
            </div>
          </>
        )}
      </body>
    </html>
  );
}
